### ISSUE TITLE
Suport for different chat format

### ISSUE THREAD

**Issue by rawk-v** [npuichigo/openai_trtllm#23]
Hi, thank you for your great work.

I would like to know if there any plan supporting different chat format like Vicuna, ChatML ?

A reference to [chat format support in llama-cpp-python](https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/llama_chat_format.py#L579)

**Comment by npuichigo** [comment]
For chat format, since I don't have too much time to track all common llm models currently, maybe at least I would give user a way to customize the roles.

**Comment by pdylanross** [comment]
I've created [a pr](https://github.com/npuichigo/openai_trtllm/pull/26) for this.

**Comment by npuichigo** [comment]
@pdylanross wow, thanks for your contribution, I'll review it when I have time today

**Comment by npuichigo** [comment]
Fixed in #26
