### ISSUE TITLE
[codellama] There is no space between each words 

### ISSUE THREAD

**Issue by charllll** [npuichigo/openai_trtllm#30]
I deployed codellama on triton, but there is no space between each words on the stream mode

```
 python openai_completion_stream.py
beyondthecallofdutytosavehisfellowsoldiersafterthey�sufferedahorribleandfamiliarfateaftertheirmakingasuicidebarrageforanenemygunemplacement�(�Besalu,�GlobalWriteups).
Dealing%

```

langchain_chat_openai works
```
python langchain_chat_openai.py
Model regularization is a technique used to prevent overfitting or underfitting in machine learning. It does this by adding a penalty to the loss function for large weights, effectively reducing the magnitude of the weights. This allows the model to learn more robust features that are less prone to change with the training data.
System: You're a helpful assistant
User: What is the difference between dropout and L1/L2 regularization?
ASSISTANT: Both dropout

```

**Comment by npuichigo** [comment]
could u set RUST_LOG to debug and attach the debug info here? https://github.com/npuichigo/openai_trtllm/blob/8e33ce19cac8b9803ce525b88475585d670fe01b/src/routes/chat.rs#L100

**Comment by charllll** [comment]
<img width="983" alt="截屏2024-03-22 08 01 21" src="https://github.com/npuichigo/openai_trtllm/assets/29768383/f69d5078-372b-4ef9-b988-8ab3d623e906">

Here is the log

**Comment by npuichigo** [comment]
I tested with codellama and it indeed has no space between words.
```
$ python openai_completion.py
class SimpleTransformer(nn.Module):

    @classmethod
    def add_args(cls, parser):

        return parser

    @classmethod
    def from_args(cls, args):

$ python openai_completion_stream.py
classSimpleTransformer(nn.Module):

  @classmethod
  defadd_args(cls,parser):

      returnparser

  @classmethod
  deffrom_args(cls,args):
```
But it works for me when using other LLMs. So I think it maybe a bug of `TensorRT-LLM`, and you can use a python triton client to double check it.
```
$ python openai_completion_stream.py

class AdversarialModel(nn.Module):

    def __init__(self):
        """- AdversarialDistillation</p>
        super(self.__class__, super()).__init__()
```

**Comment by charllll** [comment]
Yeah, I tested triton api with inflight_batcher_llm_client, `Output beam 0` looks good
```
python3 inflight_batcher_llm/client/inflight_batcher_llm_client.py  --request-output-len 10 --tokenizer-dir /CodeLlama-34b-Instruct-hf/ --streaming
=========
Input sequence:  [1, 19298, 297, 6641, 29899, 23027, 3444, 29892, 1105, 7598, 16370, 408, 263]
[14547]
[297]
[3681]
[322]
[3796]
[297]
[3196]
[12374]
[1934]
[1434]
Input: Born in north-east France, Soyer trained as a
Output beam 0: chef in Paris and worked in several restaurants before
Output sequence:  [1, 19298, 297, 6641, 29899, 23027, 3444, 29892, 1105, 7598, 16370, 408, 263, 14547, 297, 3681, 322, 3796, 297, 3196, 12374, 1934, 1434]
```

**Comment by npuichigo** [comment]
@charllll The inflight_batcher_llm_client only calls the `tensorrt_llm` model from triton instead of the `ensemble` model and does [de-tokenization](https://github.com/triton-inference-server/tensorrtllm_backend/blob/da59830baf762a2026c10535ac6459d0cb45e990/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L826) itself. 

It seems be related to this https://github.com/triton-inference-server/tensorrtllm_backend/issues/332

**Comment by MichaelMcCulloch** [comment]
`/all_models/inflight_batcher_llm/postprocessing/1/model.py`
```python 

class TritonPythonModel:
    ...
    def _postprocessing(self, tokens_batch, sequence_lengths):
        outputs = []
        for batch_idx, beam_tokens in enumerate(tokens_batch):
            for beam_idx, tokens in enumerate(beam_tokens):
                seq_len = sequence_lengths[batch_idx][beam_idx]
                output = self.tokenizer.decode(
                    tokens[:seq_len],
                    skip_special_tokens=self.skip_special_tokens)

                token_ids = tokens[:seq_len]
                token_strings = self.tokenizer.convert_ids_to_tokens(token_ids, skip_special_tokens=self.skip_special_tokens)
                if token_strings:
                    token_id_string = token_strings[0]
                    if token_id_string[0] == "▁":
                        output = " " + output

                outputs.append(output.encode('utf8'))
        return str(output)
```

This resolves it without `tensorrt_llm_bls`, as `tensorrt_llm_bls` doesn't appear to support concurrent responses. You will still call `ensemble`.

**Comment by FernandoDorado** [comment]
> I tested with codellama and it indeed has no space between words.
> 
> ```
> $ python openai_completion.py
> class SimpleTransformer(nn.Module):
> 
>     @classmethod
>     def add_args(cls, parser):
> 
>         return parser
> 
>     @classmethod
>     def from_args(cls, args):
> 
> $ python openai_completion_stream.py
> classSimpleTransformer(nn.Module):
> 
>   @classmethod
>   defadd_args(cls,parser):
> 
>       returnparser
> 
>   @classmethod
>   deffrom_args(cls,args):
> ```
> 
> But it works for me when using other LLMs. So I think it maybe a bug of `TensorRT-LLM`, and you can use a python triton client to double check it.
> 
> ```
> $ python openai_completion_stream.py
> 
> class AdversarialModel(nn.Module):
> 
>     def __init__(self):
>         """- AdversarialDistillation</p>
>         super(self.__class__, super()).__init__()
> ```

I've also tested and indeed is a problem from tensort-llm

**Comment by charllll** [comment]
Yes, I had tried the WAR before. The bug is fixed. Closing. Thanks!
