### ISSUE TITLE
The llm model must be served by triton inference server' ensemble scheduler?

### ISSUE THREAD

**Issue by zengqingfu1442** [npuichigo/openai_trtllm#35]
Can i use a single model in triton model repository?

**Comment by npuichigo** [comment]
do tokenization and de-tokenization yourself?

**Comment by zengqingfu1442** [comment]
> do tokenization and de-tokenization yourself?

yes. custom backend based on triton python backend.

**Comment by npuichigo** [comment]
If you use bls model like https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm_bls/config.pbtxt, I think it's compatible as the model inputs are compatible.

**Comment by zengqingfu1442** [comment]
![image](https://github.com/npuichigo/openai_trtllm/assets/14928378/05efd9ff-04d2-4e6d-abdf-eb6e197f9ac3)
The inputs and outputs of my custom model is above. How can i adjust my model to make it compatible?
