### ISSUE TITLE
Triton Parameter with OpenAI endpoint

### ISSUE THREAD

**Issue by FernandoDorado** [npuichigo/openai_trtllm#45]
Hello,

First of all, thank you so much for developing this tool. It works as expected, and I appreciate the immense effort that has gone into it.

I've encountered some issues with the TritonTensorRTLLM class, and your library has been incredibly helpful in resolving them. However, I have some doubts regarding the possibility of passing custom parameters through your library, parameters that I would typically send directly with Triton. Specifically, I'm interested in parameters such as repetition_penalty, top_k, length_penalty, and stop_words.

Could you please clarify if it is possible to use these custom parameters with your library? If not, is this feature on the roadmap for future releases?

I understand that these parameters are specific to TensorRT-LLM and Triton, and that the OpenAI endpoint does not directly support them.

**Comment by npuichigo** [comment]
Thank you for using it. I’m on holiday and will take a look when I’m back.

**Comment by FernandoDorado** [comment]
Hello! Is there any update on this question? :)! 

Thank you!

**Comment by npuichigo** [comment]
@FernandoDorado Sorry for the late reply. First, I think `stop_words` is supported and exposed in API. For other trtllm specific parameters, I'm not sure whether to expose them in a so-called OpenAI compatible API. Maybe it's fine since there's missing parameters in the API.

**Comment by FernandoDorado** [comment]
Okey! Thanks for your quick response. Sometimes I need to use specific parameters for triton, but I would think how to expand your solution with custom parameters in order to improve my LLM responses, specially to control the output length

**Comment by npuichigo** [comment]
To control the output length, my experience is to combine `max_tokens` with `stop_words` and it should work for most cases.
