### ISSUE TITLE
failed to run custom build command for `openai_trtllm v0.2.1 (/root/openai_trtllm)

### ISSUE THREAD

**Issue by moyerlee** [npuichigo/openai_trtllm#55]
Caused by:
  process didn't exit successfully: `/root/openai_trtllm/target/release/build/openai_trtllm-728705c75e096edb/build-script-build` (exit status: 1)
--- stdout
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/grpc_service.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/health.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/model_config.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/grpc_service.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/health.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf/model_config.proto
  cargo:rerun-if-changed=/root/openai_trtllm/triton_common/protobuf

  --- stderr
  Error: unable to compile Protocol Buffers for the Triton client
![20241014-135351](https://github.com/user-attachments/assets/bf11f484-c339-4cf4-bb98-4357020cad73)

**Comment by npuichigo** [comment]
Please follow the protobuf installation (https://grpc.io/docs/protoc-installation/) to install `protoc` before compilation.

**Comment by moyerlee** [comment]
> Please follow the protobuf installation (https://grpc.io/docs/protoc-installation/) to install `protoc` before compilation.

cool, it works!Thx!
